export const defaultServices = [
  {
    order: 1, num: '01', title: 'Flight Tickets',
    description: 'Domestic and international bookings at competitive fares across all major airlines. We compare routes, find the best pricing, and handle group bookings with ease.',
    longDescription: 'At Zamani, we handle flight bookings across all major domestic and international airlines. Our advisors compare multiple routes and fare options to get you the best combination of price, timing, and comfort. Whether you are travelling alone, with family, or as part of a group, we manage everything from initial search to final ticketing.\n\nWe work with airlines including Air India, IndiGo, Emirates, Qatar Airways, Etihad, Air Arabia, and many more. Group bookings receive dedicated negotiation with airlines to secure block fares and coordinated seating.\n\nAll tickets are issued with full itinerary details and fare rules explained clearly — so you know exactly what you are booking and what to expect at every stage.',
    highlights: ['All major domestic & international airlines', 'Group booking specialists with block fare negotiation', 'Flexible date comparison for best pricing', 'Connecting flight coordination with layover advice', 'Ticket reissue and date-change handling'],
    faqs: [
      { q: 'How far in advance should I book my flight?', a: 'For international flights, 6–8 weeks in advance typically gives the best fares. Domestic flights are best booked 3–4 weeks ahead. We can also assist with last-minute bookings when needed.' },
      { q: 'Can you help with group bookings of 10+ passengers?', a: 'Yes, we specialise in group bookings. We negotiate directly with airlines for block fares and ensure coordinated seating arrangements. Contact us with your group size and travel dates.' },
      { q: 'What happens if my flight is cancelled or delayed?', a: 'We assist with rebooking and claim processing in case of cancellations or significant delays. Our team is available 24/7 during travel for immediate support.' },
    ],
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=700&q=80',
    images: [],
    tags: ['Domestic', 'International', 'Group'], iconType: 'plane',
  },
  {
    order: 2, num: '02', title: 'Visa Services',
    description: 'End-to-end visa processing for tourism, business, study, and family visits worldwide. We manage documentation, appointments, and follow-ups on your behalf.',
    longDescription: 'Visa applications can be complex, time-consuming, and stressful. At Zamani, our visa specialists manage the entire process on your behalf — from document checklist preparation and application form completion to appointment booking, submission, and status follow-up.\n\nWe process visas for over 50 countries including UAE, Saudi Arabia, UK, USA, Schengen (Europe), Canada, Australia, Malaysia, Singapore, Thailand, and many more. Each application is reviewed for accuracy before submission to minimise rejection risk.\n\nOur team stays up to date with the latest embassy requirements, fee structures, and processing timelines — so you always get accurate, current information and the highest chance of approval.',
    highlights: ['Tourist, business, student, and family visit visas', 'Over 50 countries covered', 'Document checklist provided upfront', 'Embassy appointment booking included', 'Status tracking and follow-up until approval'],
    faqs: [
      { q: 'How long does visa processing take?', a: 'Processing times vary by country. UAE tourist visas typically take 3–5 working days. Schengen visas require 15–30 days. UK and USA visas can take 4–8 weeks. We advise applying as early as possible.' },
      { q: 'What documents are typically required?', a: 'Documents vary by country and visa type but generally include: valid passport, photographs, bank statements, employment letter, and itinerary. We provide a detailed checklist specific to your application.' },
      { q: 'Do you offer any guarantee on visa approval?', a: 'No agency can guarantee visa approval as the decision rests entirely with the embassy. However, we ensure your application is complete, accurate, and well-presented to give you the best chance.' },
    ],
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=700&q=80',
    images: [],
    tags: ['Tourist', 'Business', 'Student', 'Family'], iconType: 'passport',
  },
  {
    order: 3, num: '03', title: 'Visa Stamping',
    description: 'Professional handling of visa stamping and document attestation procedures. We coordinate directly with embassies and authorised centres to ensure accuracy and speed.',
    longDescription: 'Visa stamping involves physically placing the approved visa into your passport and is a required step for many employment and residency visas. Zamani manages the full stamping procedure — from original document submission to collection and safe return.\n\nFor employment visas particularly in GCC countries, stamping requires coordination between the employer, the consulate, and authorised typing centres. Our team handles every point of contact so there are no delays or missed steps.\n\nWe also coordinate with VFS Global, BLS International, and other authorised centres for consular appointments, ensuring your stamping is done at the earliest available slot.',
    highlights: ['Employment visa stamping for GCC countries', 'Tourist and visit visa stamping', 'Coordination with VFS Global and BLS centres', 'Original document handling with full accountability', 'Express slots secured when available'],
    faqs: [
      { q: 'What is the difference between visa approval and visa stamping?', a: 'Visa approval means the embassy has cleared you to enter the country. Visa stamping is the physical placement of that visa in your passport. Both steps are required to travel.' },
      { q: 'How long does stamping take?', a: 'Stamping times vary. UAE employment visas typically take 3–7 working days once all documents are in order. We provide a realistic timeline when you submit your documents.' },
    ],
    image: 'https://images.unsplash.com/photo-1562564055-71e051d33c19?w=700&q=80',
    images: [],
    tags: ['Embassy', 'Document', 'Attestation'], iconType: 'stamp',
  },
  {
    order: 4, num: '04', title: 'Umrah Service',
    description: 'Complete Umrah packages — flights, hotels near Haram, visas, and step-by-step guidance — for a serene and spiritually enriching pilgrimage experience.',
    longDescription: "Performing Umrah is one of the most significant journeys a Muslim undertakes. At Zamani, we treat every Umrah booking with the reverence it deserves — ensuring every detail is handled so you can focus entirely on your spiritual experience.\n\nOur packages include Saudi Arabia Umrah visa processing, return flights from Kerala, accommodation in hotels within walking distance of Masjid al-Haram in Makkah and Masjid an-Nabawi in Madinah, airport transfers, and full pre-departure briefing.\n\nWe offer group Umrah packages as well as individual and family options across multiple budget ranges. Our advisors are personally experienced with Umrah and provide guidance on all rituals, do's and don'ts, and what to expect at every stage of your pilgrimage.",
    highlights: ['Complete Umrah visa processing', 'Flights from Kerala airports', 'Hotels near Haram in Makkah and Madinah', 'Airport transfers included', 'Group and individual packages available', 'Pre-departure spiritual and practical briefing'],
    faqs: [
      { q: 'When is the best time to perform Umrah?', a: 'Umrah can be performed at any time of year. Rajab, Shaban, and Ramadan are especially significant. Outside of Hajj season, crowds are smaller and costs lower. We advise on the best timing for your situation.' },
      { q: 'What is included in the package price?', a: 'Our packages typically include visa fees, return flights, hotel accommodation (with or without meals), and airport transfers. Additional items like guided Ziyarah tours can be added. We provide a full itemised quote.' },
      { q: 'Can elderly or differently-abled pilgrims join?', a: 'Yes, we have experience arranging Umrah for elderly and differently-abled pilgrims. We coordinate wheelchair-accessible accommodation, assistance at airports, and appropriate hotel rooms.' },
    ],
    image: 'https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?w=700&q=80',
    images: [],
    tags: ['Full Package', 'Flights', 'Hotel', 'Guidance'], iconType: 'mosque',
  },
  {
    order: 5, num: '05', title: 'Holiday Packages',
    description: 'Curated holiday experiences — family, honeymoon, group, and bespoke private journeys. From beach resorts to cultural city breaks, we tailor each trip to your wishes.',
    longDescription: "A holiday should be everything you imagined — and more. Zamani designs holiday packages around what you actually want, not around what's easiest for us to sell. We listen first, build a tailored itinerary second, and handle every booking detail third.\n\nWe cover a wide range of destinations: Maldives beach escapes, Dubai city breaks, European cultural tours, Southeast Asia adventure trips, and more. For each destination we have preferred hotel and activity partners, giving you better rates and personalised service.\n\nHoneymoon packages receive special attention — from surprise room setups to candlelit dinners, we coordinate with properties to make your first trip as a couple genuinely unforgettable. Family packages include child-friendly options, connecting rooms, and age-appropriate activities.",
    highlights: ['Family, honeymoon, and group packages', 'Custom itinerary built around your preferences', 'Hotel bookings with preferred partner rates', 'Activity and excursion coordination', 'Visa assistance included where needed', 'Available across 30+ destinations worldwide'],
    faqs: [
      { q: 'How far in advance should I book a holiday package?', a: 'For peak seasons (school holidays, summer, Eid), we recommend booking 2–3 months ahead. Off-peak travel can often be arranged within 3–4 weeks. Last-minute deals are sometimes available — ask us.' },
      { q: 'Can I customise the package or use specific hotels?', a: 'Absolutely. We build packages around your preferences — specific hotels, preferred airlines, must-see activities, dietary requirements. Tell us what matters most and we build from there.' },
      { q: 'Is travel insurance included?', a: 'We strongly recommend travel insurance and can arrange it as part of your package. It covers medical emergencies, trip cancellations, and lost baggage — essential for peace of mind abroad.' },
    ],
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=700&q=80',
    images: [],
    tags: ['Family', 'Honeymoon', 'Group', 'Bespoke'], iconType: 'suitcase',
  },
  {
    order: 6, num: '06', title: 'Passport Service',
    description: 'New passport applications, renewals, corrections, and tatkal processing — all guided by our specialists who know every step and requirement of the process.',
    longDescription: "A passport is your most important travel document — and getting it right the first time saves weeks of delay. Zamani's passport service assists with new applications, renewals, corrections (name, date of birth, address), and tatkal (urgent) processing for all Indian passport holders.\n\nOur advisors check your documents for accuracy before submission to the Passport Seva Kendra, reducing the chance of rejections or resubmissions. We also assist with Granting of Police Clearance Certificates (PCC) and Emergency Certificates when needed.\n\nFor tatkal processing, we ensure all additional documentation is correctly assembled and submitted on the same day to meet the accelerated timeline.",
    highlights: ['New passport applications', 'Renewal of expired or expiring passports', 'Name, date of birth, and address corrections', 'Tatkal (urgent) processing support', 'Police Clearance Certificate (PCC) assistance', 'Document accuracy check before submission'],
    faqs: [
      { q: 'How long does passport processing take?', a: 'Regular processing takes 30–45 days from appointment date. Tatkal processing typically completes in 3–7 working days. We advise based on current Passport Seva Kendra timelines.' },
      { q: 'My passport is expiring soon — do I need to renew it before my trip?', a: 'Most countries require at least 6 months validity remaining on your passport at the time of travel. If yours expires within 6 months, we recommend renewing before booking travel.' },
      { q: 'Can you help with passports for children?', a: 'Yes, we assist with minors\' passports, which require additional documentation including birth certificate and both parents\' consent. We guide you through every step.' },
    ],
    image: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?w=700&q=80',
    images: [],
    tags: ['New', 'Renewal', 'Tatkal', 'Correction'], iconType: 'id',
  },
  {
    order: 7, num: '07', title: 'Certificate Attestation',
    description: 'Educational, personal, and commercial document attestation for global use. We handle MEA, HRD, and embassy attestations with accuracy and quick turnaround.',
    longDescription: "Documents issued in India often need attestation for use abroad — whether for employment, higher education, marriage, or business registration. Zamani manages the full attestation chain, from state-level authentication through to MEA (Ministry of External Affairs) and embassy attestation.\n\nWe handle educational documents (degrees, mark sheets, school certificates), personal documents (birth, marriage, death certificates), and commercial documents (incorporation certificates, power of attorney). Our team knows the specific requirements of each embassy and ensures the right documents are attested through the correct channels.\n\nFor apostille attestation (for Hague Convention countries), we manage the process with MEA and provide the final apostilled documents ready for use abroad.",
    highlights: ['Educational certificate attestation (degrees, mark sheets)', 'Personal document attestation (birth, marriage certificates)', 'Commercial document attestation for business use', 'MEA attestation and apostille', 'HRD attestation for educational documents', 'Embassy attestation for GCC and other countries'],
    faqs: [
      { q: 'What is the difference between attestation and apostille?', a: 'Attestation is required for countries not part of the Hague Convention (most GCC countries). Apostille is a simplified authentication for Hague Convention member countries (most of Europe, USA, Australia). We advise which is needed for your destination.' },
      { q: 'How long does attestation take?', a: 'State attestation takes 5–10 working days. MEA attestation adds another 3–7 days. Embassy attestation varies by country. Full attestation for GCC employment typically takes 3–4 weeks. Express options are sometimes available.' },
    ],
    image: 'https://images.unsplash.com/photo-1568219656418-15c329312bf1?w=700&q=80',
    images: [],
    tags: ['Educational', 'Personal', 'Commercial', 'MEA'], iconType: 'document',
  },
  {
    order: 8, num: '08', title: 'Travel Insurance',
    description: 'Comprehensive coverage that keeps you protected from departure to return. Medical emergencies, trip cancellations, lost baggage — covered, clearly explained.',
    longDescription: "Travel insurance is not an afterthought — it is the safety net that makes international travel truly worry-free. Zamani offers comprehensive travel insurance policies covering medical emergencies, hospitalisation abroad, emergency evacuation, trip cancellation, flight delays, and lost or delayed baggage.\n\nWe work with leading insurance providers to offer policies suited to different trip types: single-trip, multi-trip annual plans, student plans, and senior citizen plans. Schengen visa applicants receive policies that specifically meet embassy requirements.\n\nOur advisors explain coverage in plain language — what is covered, what is not, and how to claim if needed. We also assist with claim filing support after your return, making an already stressful situation more manageable.",
    highlights: ['Medical emergency and hospitalisation coverage', 'Trip cancellation and interruption protection', 'Flight delay and missed connection cover', 'Lost, stolen, or delayed baggage coverage', 'Emergency medical evacuation', 'Schengen-compliant policies available'],
    faqs: [
      { q: 'Is travel insurance mandatory?', a: 'For Schengen visas, travel insurance with minimum €30,000 medical coverage is mandatory. For other destinations, it is highly recommended. Some countries also require specific coverage levels for visa approval.' },
      { q: 'What is typically not covered by travel insurance?', a: 'Pre-existing medical conditions (unless declared), adventure sports (unless a specific rider is added), self-inflicted injuries, and claims arising from travelling against government advisories are generally excluded. We explain all exclusions before you purchase.' },
    ],
    image: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=700&q=80',
    images: [],
    tags: ['Medical', 'Trip Cancel', 'Baggage'], iconType: 'shield',
  },
  {
    order: 9, num: '09', title: 'GCC Job Visa',
    description: 'Verified employment visas for UAE, Saudi Arabia, Qatar, Oman, Kuwait, and Bahrain. We guide workers through medical tests, attestation, stamping, and final approval.',
    longDescription: "GCC employment visas require careful preparation across multiple stages — and each stage has consequences if not handled correctly. Zamani manages the complete process for workers heading to UAE, Saudi Arabia, Qatar, Oman, Kuwait, and Bahrain: from document collection and attestation through to medical fitness tests, GAMCA (Gulf Approved Medical Centre Association) coordination, visa stamping, and departure.\n\nWe work with verified employers and recruitment agents and do not process visas without confirming the authenticity of the offer letter and company. Our advisors ensure all documents are correctly attested for the specific destination country, reducing delays at immigration.\n\nWe also advise on labor rights, contract review, and what to carry at the airport — so workers arrive prepared and protected.",
    highlights: ['UAE, Saudi, Qatar, Oman, Kuwait, Bahrain covered', 'Document attestation and verification', 'GAMCA medical test coordination', 'Visa stamping and travel clearance', 'Departure airport assistance', 'Contract and offer letter review'],
    faqs: [
      { q: 'How do I know if my job offer is genuine?', a: 'We verify all job offers before processing visas. We check company registration, offer letter authenticity, and MOFA approval. If something does not look right, we tell you — protecting workers from fraud is a priority.' },
      { q: 'What medical tests are required for GCC visas?', a: 'Most GCC countries require tests for tuberculosis, HIV, hepatitis B and C, and general fitness. Tests must be done at GAMCA-approved centres. We coordinate your appointment and handle the medical certificate submission.' },
      { q: 'How long does the GCC job visa process take?', a: 'From document collection to final stamping, the process typically takes 3–6 weeks depending on the country and employer responsiveness. We provide a realistic timeline at the start.' },
    ],
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=700&q=80',
    images: [],
    tags: ['UAE', 'Saudi', 'Qatar', 'Oman'], iconType: 'work',
  },
  {
    order: 10, num: '10', title: 'Holyland Services',
    description: 'Sacred journeys to Mecca, Madinah, and Jerusalem with full pilgrimage assistance. We arrange group and individual tours with experienced guides and coordinated logistics.',
    longDescription: "The Holyland — Jerusalem, Bethlehem, Nazareth, and the surrounding sacred sites — holds profound significance for Christians and pilgrims worldwide. Zamani arranges group and individual Holy Land tours with experienced local guides, coordinated transportation, and accommodation close to major sites.\n\nWe also arrange extended pilgrimage journeys that combine Makkah, Madinah, and Jerusalem — particularly popular among Muslims who wish to combine Umrah with a visit to Masjid al-Aqsa. All logistics including visas, flights, and accommodation are managed by our team.\n\nOur guides are experienced and knowledgeable about the historical and religious significance of each site, providing meaningful context to every visit rather than just transportation.",
    highlights: ['Jerusalem, Bethlehem, and Nazareth tours', 'Combined Umrah and Holyland packages', 'Experienced local guides at all sites', 'Group and individual tour options', 'Full visa and flight management', 'Accommodation near major holy sites'],
    faqs: [
      { q: 'Is a visa required to visit Jerusalem?', a: 'Israel requires a tourist visa for Indian passport holders (applied online via ETA). Some Palestinian Authority areas are accessible separately. We handle all visa requirements for your specific itinerary.' },
      { q: 'Are combined Umrah + Jerusalem tours available?', a: 'Yes, we arrange combined packages covering Makkah, Madinah, and Jerusalem in a single trip. These are particularly popular during off-peak Umrah seasons.' },
    ],
    image: 'https://images.unsplash.com/photo-1565179153197-33c59cf3a7fc?w=700&q=80',
    images: [],
    tags: ['Mecca', 'Jerusalem', 'Group Tour'], iconType: 'temple',
  },
  {
    order: 11, num: '11', title: 'Forex Services',
    description: 'Foreign currency, travel cards, and remittance at transparent, competitive rates. We handle 30+ currencies with no hidden markups — know exactly what you pay.',
    longDescription: "Foreign exchange is often an afterthought in travel planning — and that is when travellers lose money to poor rates and hidden markups. At Zamani, we offer transparent forex services with competitive rates across 30+ currencies, no hidden fees, and clear documentation of every transaction.\n\nWe supply physical foreign currency notes for travel, travel prepaid cards (useful for multiple currencies and ATM withdrawals abroad), and inward/outward remittance for personal and business purposes.\n\nAll forex transactions are fully RBI-compliant and carried out under our authorised money changer licence. Rate quotes are given in advance so you know exactly how many rupees you are spending per unit of foreign currency.",
    highlights: ['Physical currency in 30+ denominations', 'Multi-currency travel prepaid cards', 'Competitive rates with no hidden markups', 'Inward and outward remittance', 'RBI-compliant authorised money changer', 'Rate locked at time of booking'],
    faqs: [
      { q: 'When should I buy foreign currency?', a: 'Rates fluctuate daily. We recommend buying 2–5 days before travel when you are ready to commit. We provide current rates on request and can lock them for same-day collection.' },
      { q: 'Are travel cards better than carrying cash?', a: 'Cards are safer (replaceable if lost) and accepted at most international establishments. Cash is useful for small purchases and in areas with limited card acceptance. We recommend a combination of both.' },
      { q: 'Can I sell unused foreign currency back?', a: 'Yes, we accept buy-back of most major currencies at prevailing rates. Bring your original purchase receipt and passport for the transaction.' },
    ],
    image: 'https://images.unsplash.com/photo-1580519542036-c47de6196ba5?w=700&q=80',
    images: [],
    tags: ['Currency', 'Travel Card', 'Remittance'], iconType: 'forex',
  },
];

export const defaultTestimonials = [
  { stars: 5, quote: "Zamani arranged our family's Umrah end-to-end. From the visa to the hotel near Haram — everything was exactly as promised. Will return for our next pilgrimage.", author: 'Fathima A.', role: 'Umrah Client · 2024', initials: 'FA' },
  { stars: 5, quote: 'Got my GCC job visa processed in record time. The team handled my attestation, medical and stamping while I was still in India. Genuinely impressed.', author: 'Rashid M.', role: 'Job Visa · Dubai', initials: 'RM' },
  { stars: 5, quote: 'Booked our Maldives honeymoon through Zamani. Forex, flights, hotel — one call, one invoice. Clean, transparent, and they actually pick up the phone.', author: 'Sajid & Khadija', role: 'Honeymoon · Maldives', initials: 'SK' },
];

export const defaultDestinations = [
  { order: 1, name: 'Umrah · Mecca', country: 'Saudi Arabia', price: 'From ₹78,000', image: 'https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?w=1200&q=80', badge: 'Featured' },
  { order: 2, name: 'Dubai', country: 'UAE', price: '₹52,000', image: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800&q=80', badge: '' },
  { order: 3, name: 'Maldives', country: 'Indian Ocean', price: '₹89,000', image: 'https://images.unsplash.com/photo-1539367628448-4bc5c9d171c8?w=800&q=80', badge: '' },
  { order: 4, name: 'Istanbul', country: 'Türkiye', price: '₹68,000', image: 'https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=800&q=80', badge: '' },
  { order: 5, name: 'Paris', country: 'France', price: '₹1,12,000', image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80', badge: '' },
];

export const defaultProcessSteps = [
  { order: 1, num: '01', title: 'Tell Us Your Plan', description: "Start with a call, WhatsApp message, or a walk-in visit. Tell us what you need — whether it's a flight, a visa, an Umrah package, or something you're not sure about yet.", items: ['Free initial consultation — no commitment', 'Available by call, WhatsApp, or in-person', 'We listen first, advise second', 'Response within the same working day'], image: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80', tag: 'Free Consultation' },
  { order: 2, num: '02', title: 'Get a Tailored Quote', description: "We build the right package or document solution around your needs — transparently, with no hidden fees. You see exactly what you're paying for, and why.", items: ['Itemised, transparent pricing', 'Multiple options across budgets', 'No hidden charges — ever', 'Quote sent by WhatsApp or email'], image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80', tag: 'Same-day Quote' },
  { order: 3, num: '03', title: 'We Handle Everything', description: 'Once you confirm, your dedicated advisor takes over. Bookings, visas, attestations, insurance, forex — all coordinated and tracked. You receive updates at every stage.', items: ['Dedicated advisor for your case', 'Document checklist provided upfront', 'Embassy, airline, and hotel coordination', 'Regular status updates via WhatsApp'], image: 'https://images.unsplash.com/photo-1568219656418-15c329312bf1?w=800&q=80', tag: 'Fully Managed' },
  { order: 4, num: '04', title: 'Travel With Peace', description: "Step out with all documents in hand, pre-travel briefing completed, and our support number saved. We're on call from departure to safe return — for anything that comes up.", items: ['Documents delivered before travel', 'Pre-departure briefing included', '24/7 support line for emergencies', 'Post-travel follow-up for repeat needs'], image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80', tag: 'Bon Voyage' },
];

export const defaultBlogPosts = [
  { title: '10 Essential Documents for Your Umrah Journey — The Complete 2026 Checklist', excerpt: 'Planning your Umrah is a spiritual commitment. Making sure your paperwork is correct is our job. Here is the definitive document list every pilgrim needs — from passport requirements to hotel booking confirmations and medical certificates.', content: 'Full article content here...', image: 'https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?w=1200&q=80', category: 'Umrah', date: '2026-05-12', readTime: '8 min', featured: true },
  { title: 'GCC Job Visa: Complete Guide for Indian Workers in 2026', excerpt: 'Everything you need to know about the GCC employment visa process, from document preparation to stamping.', content: 'Full article content here...', image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=700&q=80', category: 'GCC Work', date: '2026-05-08', readTime: '6 min', featured: false },
  { title: 'Best Destinations for Indian Passport Holders in 2026', excerpt: 'Visa-on-arrival, e-visa, and visa-free destinations for Indian passport holders — updated for 2026.', content: 'Full article content here...', image: 'https://images.unsplash.com/photo-1539367628448-4bc5c9d171c8?w=700&q=80', category: 'Destinations', date: '2026-05-04', readTime: '5 min', featured: false },
  { title: 'How to Apply for a Schengen Visa from India — 2026 Guide', excerpt: "Everything you need to know about documents, bank statements, itineraries, and appointment booking for Europe's most popular visa.", content: 'Full article content here...', image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=700&q=80', category: 'Visa Guides', date: '2026-04-20', readTime: '6 min', featured: false },
  { title: 'Maldives Honeymoon: Planning the Perfect Trip from Kerala', excerpt: 'Budget tips, best resorts, flight options, and the forex rates you need to know before your dream honeymoon getaway.', content: 'Full article content here...', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=700&q=80', category: 'Destinations', date: '2026-04-14', readTime: '5 min', featured: false },
  { title: 'Dubai Visit Visa: 30-Day vs 60-Day — Which Is Right for You?', excerpt: 'A clear comparison of UAE visitor visa types, costs, extensions, and what documents you actually need to submit.', content: 'Full article content here...', image: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=700&q=80', category: 'Visa Guides', date: '2026-04-07', readTime: '4 min', featured: false },
];

export const defaultHomeContent = {
  heroTitle: 'Journeys,',
  heroTitleEm: 'crafted',
  heroTitleSuffix: 'with quiet luxury.',
  heroLead: 'From flight tickets and Umrah pilgrimage to GCC job visas and forex — Zamani is the single, trusted desk for everything that takes you across borders.',
  heroImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1920&q=80',
  heroBadgeNum: '15+',
  heroBadgeLabel: 'Years of crafting trusted journeys across the world',
  heroMetaLeft: 'Tours · Visa · Forex',
  heroMetaTrust: 'Trusted by 12,000+ travellers',
  marqueeItems: ['Flight Tickets', 'Visa Services', 'Umrah Pilgrimage', 'Holiday Packages', 'Passport Service', 'Travel Insurance', 'GCC Job Visa', 'Forex Services'],
  aboutTitle: 'A travel house built on',
  aboutTitleEm: 'trust,',
  aboutTitleSuffix: 'precision, and care.',
  aboutP1: 'For over a decade, Zamani Tours & Travels has been the chosen partner for thousands of travellers, pilgrims, and professionals navigating the world. We blend the warmth of personal service with the discipline of seasoned documentation experts.',
  aboutP2: "Whether it is your first Umrah, a long-awaited family holiday, a GCC career move, or simply the right currency at the right rate — every detail is handled by people who treat your journey as their own.",
  statYears: '15+',
  statClients: '12K+',
  statServices: '11',
  aboutImg1: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=900&q=80',
  aboutImg2: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=700&q=80',
};

export const defaultSiteSettings = {
  phone1: '859 2002 549',
  phone2: '859 2002 584',
  phone3: '859 2002 529',
  phone4: '859 2042 002',
  email: 'info@zamanitours.com',
  address: 'Kerala, India',
  instagram: '#',
  facebook: '#',
  whatsapp: 'https://wa.me/918592002549',
  linkedin: '#',
  logoUrl: '/images/zamaniLogo.svg',
  bannerServices: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1920&q=80',
  bannerBlog: 'https://images.unsplash.com/photo-1488085061387-422e29b40080?w=1920&q=80',
  bannerProcess: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1920&q=80',
  bannerContact: 'https://images.unsplash.com/photo-1423666639041-f56000c27a9a?w=1920&q=80',
  brandName: 'Zamani',
  brandSubtitle: 'Tours & Travels',
  showBrandText: true,
};

export const defaultAboutContent = {
  heroTitle: 'Crafted with',
  heroTitleEm: 'trust,',
  heroTitleSuffix: 'for fifteen years.',
  heroLead: 'From a modest office in Kerala to a full-service travel house trusted by over 12,000 clients — every journey at Zamani begins with care and ends with satisfaction.',
  heroImage: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=1920&q=80',
  storyP1: 'For over a decade, Zamani Tours & Travels has been the chosen partner for thousands of travellers, pilgrims, and professionals navigating the world. We blend the warmth of personal service with the discipline of seasoned documentation experts.',
  storyP2: 'Founded in 2010, we began by helping families apply for their first passports and book flights to the Gulf. Today, our desk handles everything from Umrah pilgrimage packages and GCC job visas to international holiday packages, forex, and certificate attestation — under one roof, by people who care.',
  storyP3: "Our clients don't just come to us for a visa or a ticket. They come back because they trust us — with their time, their money, and often, the most significant journeys of their lives.",
  storyImg1: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=900&q=80',
  storyImg2: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=700&q=80',
  values: [
    { title: 'Trust & Accountability', description: 'We are a licensed, registered travel agency. Every document we handle is processed with the same care you would expect from a family advisor — not a transaction desk.' },
    { title: 'On-Time, Every Time', description: "Travel has deadlines that can't slip. We commit to timelines and honour them — visas, passports, attestations, and tickets all delivered when we say they will be." },
    { title: 'Real Human Support', description: 'A dedicated advisor — not a chatbot or a call queue. Reach us on WhatsApp, by phone, or walk into our office. We are here when you need us most.' },
    { title: 'Transparent Pricing', description: 'No hidden fees. No surprises. You receive a clear, itemised quote before we begin. What we quote is what you pay — and we tell you exactly why.' },
    { title: 'Community First', description: 'We grew up serving the families of Kerala. Their trust built us, and we carry that responsibility forward — handling each enquiry as if it came from our own neighbourhood.' },
    { title: 'Global Reach, Local Heart', description: 'We work with embassies, airlines, hotels, and attestation authorities worldwide — but our service is always personal, always local, always yours.' },
  ],
  timeline: [
    { year: '2010', title: 'Founded in Kerala', description: 'Zamani Tours & Travels opens its first desk — focused on flight bookings and passport assistance for Gulf workers and their families.' },
    { year: '2013', title: 'Visa Services Launched', description: 'Expanded into full visa processing for UAE, Saudi Arabia, and Qatar — quickly becoming a trusted name for GCC employment documentation.' },
    { year: '2015', title: 'Umrah Division Established', description: 'Launched dedicated Umrah packages, combining flights, accommodation near Haram, and complete guidance — serving pilgrims with the care the journey deserves.' },
    { year: '2018', title: 'Forex & Certificate Attestation Added', description: 'Expanded into foreign currency exchange and document attestation services, making Zamani a true single-desk solution for international needs.' },
    { year: '2021', title: '10,000 Clients Milestone', description: 'Crossed 10,000 satisfied clients — a testament to the trust families and professionals across Kerala place in us year after year.' },
    { year: '2025', title: 'Eleven Services, One Trusted Desk', description: 'Today, Zamani offers eleven specialised services — from Holyland tours and travel insurance to holiday packages for every budget and occasion.' },
  ],
};
